# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('hostname_type', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=40)),
                ('extrainfo', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('conf', models.CharField(max_length=40)),
                ('cpe', models.CharField(max_length=40)),
                ('time', models.DateField()),
            ],
        ),
    ]
