# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_result_sqlmap_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlmap',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sqlmap',
            name='dbms',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sqlmap',
            name='query',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sqlmap',
            name='suffix',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sqlmap',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
