# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.CharField(max_length=10)),
                ('content_type', models.CharField(max_length=30)),
                ('content_length', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('scheme', models.CharField(max_length=30)),
                ('path', models.TextField()),
                ('header', models.TextField()),
                ('content', models.TextField()),
                ('request_header', models.TextField()),
                ('request_content', models.TextField()),
                ('data_start', models.DateField(auto_now_add=True)),
                ('data_end', models.DateField(auto_now=True)),
                ('extension', models.TextField()),
                ('port', models.CharField(max_length=10)),
            ],
        ),
    ]
