# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-23 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_result_sqlmap_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 17, 50, 50, 564954)),
        ),
    ]
