# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-24 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_auto_20180323_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='filter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_packet', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('parm', models.TextField()),
                ('status', models.CharField(default=b'0', max_length=10)),
                ('taskid', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='inject_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=50)),
                ('packet', models.TextField(default=b'')),
                ('url', models.TextField(default=b'')),
                ('query', models.TextField(default=b'')),
                ('post_data', models.TextField(default=b'', null=True)),
                ('dbms', models.TextField(default=b'')),
                ('suffix', models.TextField(default=b'')),
                ('run_status', models.CharField(default=b'', max_length=50)),
                ('status', models.CharField(default=b'0', max_length=10)),
                ('options', models.TextField(default=b'')),
                ('clause', models.CharField(default=b'', max_length=20)),
                ('notes', models.TextField(default=b'')),
                ('ptype', models.CharField(default=b'', max_length=20)),
                ('dbms_version', models.CharField(default=b'', max_length=20)),
                ('prefix', models.TextField(default=b'')),
                ('place', models.TextField(default=b'')),
                ('vul_info', models.CharField(default=b'', max_length=100)),
                ('os', models.TextField(default=b'', null=True)),
                ('parameter', models.CharField(default=b'', max_length=20)),
                ('detail', models.TextField(default=b'')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 3, 24, 13, 51, 50, 798538))),
            ],
        ),
        migrations.CreateModel(
            name='proxy_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(default=b'')),
                ('url', models.TextField(default=b'')),
                ('method', models.CharField(default=b'', max_length=20)),
                ('request_headers', models.TextField(default=b'')),
                ('scheme', models.TextField(default=b'')),
                ('path', models.TextField(default=b'')),
                ('request_cookies', models.TextField(default=b'')),
                ('port', models.CharField(default=b'', max_length=20)),
                ('status_code', models.CharField(default=b'', max_length=20)),
                ('response_headers', models.TextField(default=b'')),
                ('response_content', models.TextField(default=b'')),
                ('date', models.TimeField(auto_now=True)),
                ('request_content', models.TextField()),
                ('http_version', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='scan',
        ),
        migrations.DeleteModel(
            name='Sqlmap',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
