# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_auto_20170514_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlmap',
            name='taskid',
            field=models.CharField(max_length=50),
        ),
    ]
