# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_headers', models.TextField()),
                ('method', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('path', models.TextField()),
                ('host', models.TextField()),
                ('port', models.CharField(max_length=20)),
                ('status_code', models.CharField(max_length=20)),
                ('response_headers', models.TextField()),
                ('response_content', models.TextField()),
                ('scheme', models.TextField()),
                ('date', models.TimeField(auto_now=True)),
                ('request_content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
