# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-24 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_auto_20180324_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inject_data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 14, 17, 1, 138757)),
        ),
    ]
