# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_auto_20170514_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='host',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='method',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='port',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='request_cookies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='request_headers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='response_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='response_headers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='scheme',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='status_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
