# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_auto_20170515_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlmap',
            name='options',
            field=models.TextField(default=''),
        ),
    ]
