# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-24 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_auto_20180324_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inject_data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 17, 35, 59, 745642)),
        ),
    ]
