# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_sqlmap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlmap',
            name='data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
