# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_auto_20170515_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlmap',
            name='data',
            field=models.TextField(default='null'),
        ),
    ]
