# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_auto_20170515_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlmap',
            old_name='data',
            new_name='post_data',
        ),
    ]
