# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0011_auto_20170515_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlmap',
            name='parameter',
            field=models.CharField(default='', max_length=20),
        ),
    ]
